alias l3d='source ~/repo/scripts/l3d'
alias dpsa="docker ps -a"
alias dli='docker images'
alias drmi='docker rmi'
alias ebash='vim ~/.bashrc'
alias fresh='source ~/.bashrc'
alias laa='vim ~/.bash_aliases'
alias efunc='vim ~/.functions.sh'
alias vlr='source ~/repo/scripts/vlr'
alias ghis='git log --graph --oneline --decorate --all'
alias gsh='git show'
alias gdiff='git diff'

alias p3='python3'
alias so='source'
